/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin Hannahs-Mac-mini.local 18.7.0 x86_64"
#define LGL_COMPILED "Wed Dec 18 11:35:34 PST 2019"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
